version: '3'

services:
  proxy:
    image: dockercloud/haproxy
    networks: 
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 1936:1936 # for stats page (basic auth. stats:stats)

networks:
  proxy:
    external:
      name: proxy