version: '3'

services:
  app:
    image: nginx:latest
    volumes:
      - .:/usr/share/nginx/html/
    expose:
      - "80"
    networks: 
      - proxy

networks:
  proxy:
    external:
      name: proxy