version: '3'

services:
  app:
    image:  dockersamples/visualizer
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      - VIRTUAL_HOST=viz.org
      - SERVICE_PORTS=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - proxy

networks:
  proxy:
    external:
      name: proxy