version: '3'

services:
  app:
    image:  dockersamples/visualizer
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - proxy

networks:
  proxy:
    external:
      name: proxy